### ISSUE TITLE
how to do math!!!!

### ISSUE THREAD

**Issue by RishiKirubhakar** [frc-862/new-rookie-teachings#23]

**Comment by RishiKirubhakar** [comment]
hi
hi
hi
hih
h
ih
hih
ihi
h
ih
hi
ih
ihhi

**Comment by AarushDahanuwala** [comment]
1+1=11

**Comment by Tar-code-hi** [comment]
1+1=2
2+2=4
4-2=2
2*2=4
1*2=2
4*2=8
8/4=2

**Comment by RishiKirubhakar** [comment]
nice tar

**Comment by AarushDahanuwala** [comment]
1+1 = window
2+2 = fish
3+3 = infiintie or 8
4+4 = 16

**Comment by Tar-code-hi** [comment]
All I heard was infinite fish, and that is good enough
